RandomForestClassifier



predicit whether the person have diabetes or not

Project Section

Diabetes Prediction Model

Description: Developed a machine learning model to predict the likelihood of diabetes in individuals using the Random Forest algorithm.

Tech Stack: Python, Scikit-Learn, Pandas, Numpy, Matplotlib, Jupyter Notebook

Key Responsibilities:

Preprocessed and cleaned the dataset to handle missing values and outliers.
Performed feature selection and engineering to improve model accuracy.
Trained and optimized a Random Forest classifier to achieve high prediction accuracy.
Evaluated the model using metrics such as accuracy, precision, recall, and F1-score.
Visualized the results and model performance using Matplotlib.
Outcome: Achieved an accuracy of XX% in predicting diabetes, demonstrating the model's effectiveness and robustness.

In [2]:
import numpy as np # array calculations
import pandas as pd # read the data
import matplotlib.pyplot as plt # plot the graph
import seaborn as sns # plot graph in graphical way

In [3]:
Data=pd.read_csv("diabetes.csv") # read the dataset

In [4]:
Data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [5]:
Data.shape

(768, 9)

In [6]:
Data.head() # to display the firt five rows in data set

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

AIM

a simple machine learning project

according to the datas collected predicting whether the person have diabetes or not 


the data contains features like 

1.pregnancies
2.glucose
3.bloodpressure
4.skinthickness
5.insulin
6.BMI
7.diabetespedigreefunction
8.age

our output(label) is Outcome


In [7]:
Data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [8]:
Data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [9]:
Data.shape # how many rows and columns in dataset

(768, 9)

In [10]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [11]:
Data.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [13]:
Data.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [14]:
Data.isnull()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin    BMI  \
0          False    False          False          False    False  False   
1          False    False          False          False    False  False   
2          False    False          False          False    False  False   
3          False    False          False          False    False  False   
4          False    False          False          False    False  False   
..           ...      ...            ...            ...      ...    ...   
763        False    False          False          False    False  False   
764        False    False          False          False    False  False   
765        False    False          False          False    False  False   
766        False    False          False          False    False  False   
767        False    False          False          False    False  False   

     DiabetesPedigreeFunction    Age  Outcome  
0                       False  False    False  
1                       False  False    False  
2                       False  False    False  
3                       False  False    False  
4                       False  False    False  
..                        ...    ...      ...  
763                     False  False    False  
764                     False  False    False  
765                     False  False    False  
766                     False  False    False  
767                     False  False    False  

[768 rows x 9 columns]

In [15]:
Data.isnull().sum() # to check if there is any null values in data set. if there is null value then use this code    df.dropna()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [16]:
Data.isnull().any()

Pregnancies                 False
Glucose                     False
BloodPressure               False
SkinThickness               False
Insulin                     False
BMI                         False
DiabetesPedigreeFunction    False
Age                         False
Outcome                     False
dtype: bool

In [17]:
Data.dropna() #if any NaN values in the data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [18]:
Data.corr()

Pregnancies   Glucose  BloodPressure  SkinThickness  \
Pregnancies                  1.000000  0.129459       0.141282      -0.081672   
Glucose                      0.129459  1.000000       0.152590       0.057328   
BloodPressure                0.141282  0.152590       1.000000       0.207371   
SkinThickness               -0.081672  0.057328       0.207371       1.000000   
Insulin                     -0.073535  0.331357       0.088933       0.436783   
BMI                          0.017683  0.221071       0.281805       0.392573   
DiabetesPedigreeFunction    -0.033523  0.137337       0.041265       0.183928   
Age                          0.544341  0.263514       0.239528      -0.113970   
Outcome                      0.221898  0.466581       0.065068       0.074752   

                           Insulin       BMI  DiabetesPedigreeFunction  \
Pregnancies              -0.073535  0.017683                 -0.033523   
Glucose                   0.331357  0.221071                  0.137337   
BloodPressure             0.088933  0.281805                  0.041265   
SkinThickness             0.436783  0.392573                  0.183928   
Insulin                   1.000000  0.197859                  0.185071   
BMI                       0.197859  1.000000                  0.140647   
DiabetesPedigreeFunction  0.185071  0.140647                  1.000000   
Age                      -0.042163  0.036242                  0.033561   
Outcome                   0.130548  0.292695                  0.173844   

                               Age   Outcome  
Pregnancies               0.544341  0.221898  
Glucose                   0.263514  0.466581  
BloodPressure             0.239528  0.065068  
SkinThickness            -0.113970  0.074752  
Insulin                  -0.042163  0.130548  
BMI                       0.036242  0.292695  
DiabetesPedigreeFunction  0.033561  0.173844  
Age                       1.000000  0.238356  
Outcome                   0.238356  1.000000

In [19]:
Data.cov()

Pregnancies      Glucose  BloodPressure  \
Pregnancies                 11.354056    13.947131       9.214538   
Glucose                     13.947131  1022.248314      94.430956   
BloodPressure                9.214538    94.430956     374.647271   
SkinThickness               -4.390041    29.239183      64.029396   
Insulin                    -28.555231  1220.935799     198.378412   
BMI                          0.469774    55.726987      43.004695   
DiabetesPedigreeFunction    -0.037426     1.454875       0.264638   
Age                         21.570620    99.082805      54.523453   
Outcome                      0.356618     7.115079       0.600697   

                          SkinThickness       Insulin         BMI  \
Pregnancies                   -4.390041    -28.555231    0.469774   
Glucose                       29.239183   1220.935799   55.726987   
BloodPressure                 64.029396    198.378412   43.004695   
SkinThickness                254.473245    802.979941   49.373869   
Insulin                      802.979941  13281.180078  179.775172   
BMI                           49.373869    179.775172   62.159984   
DiabetesPedigreeFunction       0.972136      7.066681    0.367405   
Age                          -21.381023    -57.143290    3.360330   
Outcome                        0.568747      7.175671    1.100638   

                          DiabetesPedigreeFunction         Age   Outcome  
Pregnancies                              -0.037426   21.570620  0.356618  
Glucose                                   1.454875   99.082805  7.115079  
BloodPressure                             0.264638   54.523453  0.600697  
SkinThickness                             0.972136  -21.381023  0.568747  
Insulin                                   7.066681  -57.143290  7.175671  
BMI                                       0.367405    3.360330  1.100638  
DiabetesPedigreeFunction                  0.109779    0.130772  0.027472  
Age                                       0.130772  138.303046  1.336953  
Outcome                                   0.027472    1.336953  0.227483

TRAIN AND TEST


In [20]:
import sklearn
from sklearn.model_selection import train_test_split  # for this train and test split function we need to parameters , they are data and label , or it means input and output


In [21]:
X=Data.iloc[ : ,Data.columns!="Outcome"] #df.iloc[:, df.columns != "Outcome"] selects all rows and columns where the column name is not "Outcome".
Y=Data.iloc[ : ,Data.columns=="Outcome"]  # df.iloc[:, df.columns == "Outcome"] selects all rows and the column where the column name is "Outcome".

In [22]:
print(X)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  


In [23]:
print(Y)

     Outcome
0          1
1          0
2          1
3          0
4          1
..       ...
763        0
764        0
765        0
766        1
767        0

[768 rows x 1 columns]


A train-test split function typically requires two main variables: the features (data) and the labels (target variable). However, additional parameters are often used to control the splitting process.


Basic Usage

Required Variables

Features (X): The input data (independent variables) used to train the model.

Labels (Y): The target variable (dependent variable) used to evaluate the model.

Additional Parameters


test_size: Proportion of the dataset to include in the test split (e.g., 0.2 means 20% of the data will be used for testing).

train_size: Proportion of the dataset to include in the train split (optional if test_size is specified).

random_state: Controls the shuffling applied to the data before splitting (useful for reproducibility).


shuffle: Whether or not to shuffle the data before splitting (default is True).



Output

The function returns four variables:

X_train: Training data for features.

X_test: Testing data for features.

Y_train: Training data for labels.

Y_test: Testing data for labels.


In [34]:
xtrain,xtest,ytrain , ytest =train_test_split(X,Y,test_size=0.2)  #20% of the data for test

In [35]:
xtrain.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
458           10      148             84             48      237  37.6   
260            3      191             68             15      130  30.9   
714            3      102             74              0        0  29.5   
35             4      103             60             33      192  24.0   
5              5      116             74              0        0  25.6   

     DiabetesPedigreeFunction  Age  
458                     1.001   51  
260                     0.299   34  
714                     0.121   32  
35                      0.966   33  
5                       0.201   30

In [36]:
xtest.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
737            8       65             72             23        0  32.0   
61             8      133             72              0        0  32.9   
206            8      196             76             29      280  37.5   
442            4      117             64             27      120  33.2   
666            4      145             82             18        0  32.5   

     DiabetesPedigreeFunction  Age  
737                     0.600   42  
61                      0.270   39  
206                     0.605   57  
442                     0.230   24  
666                     0.235   70

In [37]:
xtrain.shape

(614, 8)

In [38]:
xtest.shape

(154, 8)

In [39]:
ytrain.head()

Outcome
458        1
260        0
714        0
35         0
5          0

In [40]:
ytest.head()

Outcome
737        0
61         1
206        1
442        0
666        1

In [41]:
ytrain.shape

(614, 1)

In [42]:
ytest.shape

(154, 1)

RANDOMFOREST ALGORITHM


In [44]:
from sklearn.ensemble import RandomForestClassifier

In [45]:
Model_RF=RandomForestClassifier()

In [46]:
Model_RF.fit(xtrain,ytrain) # to train the algorithm #model.fit(xtrain,ytrain.values.ravel())

C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier()

In [47]:
Model_RF.predict(xtest) # to test the algorithm using test data

array([0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1],
      dtype=int64)

In [51]:
prediction=Model_RF.predict(xtest)

In [52]:
prediction

array([0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1],
      dtype=int64)

In [48]:
ytest

Outcome
737        0
61         1
206        1
442        0
666        1
..       ...
660        0
13         1
424        1
326        1
221        1

[154 rows x 1 columns]

In [53]:
from sklearn.metrics import accuracy_score

In [55]:
accuracy_score(prediction,ytest)



0.7272727272727273

TO PREDICT THE OUTPUT FOR NEW INPUT 

In [56]:
Model_RF.predict(np.array([[6,148,72,35,0,33.6,0.627,50]]))

C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [58]:
# Predict for a new input
new_input = np.array([[6, 148, 72, 35, 0, 33.6, 0.627, 50]])  # Example input
Model_RF.predict(new_input)


C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [59]:
Model_RF.predict([[6, 148, 72, 35, 0, 33.6, 0.627, 50]])

C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

YOU TUBE LINK FOR THE CODE , https://www.youtube.com/watch?v=SM1kNV8eeU0&list=PLzvG6SljmrLhzWz1lM-lAsqXVB4wAl3yY&index=1

In [60]:
Model_RF.predict([[6, 148, 72, 35, 0, 33.6, 0.627, 50]])

C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)