Aim : use a Regression algorithm in machine learning to predict a conformed cases based on training a algorithm

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

#import warnings
#warnings.filterwarnings('ignore')

In [3]:
Data=pd.read_csv("covid_19_india.csv")
Data

Sno      Date     Time State/UnionTerritory ConfirmedIndianNational  \
0        1  30/01/20  6:00 PM               Kerala                       1   
1        2  31/01/20  6:00 PM               Kerala                       1   
2        3  01/02/20  6:00 PM               Kerala                       2   
3        4  02/02/20  6:00 PM               Kerala                       3   
4        5  03/02/20  6:00 PM               Kerala                       3   
...    ...       ...      ...                  ...                     ...   
1441  1442  29/04/20  5:00 PM            Telengana                       -   
1442  1443  29/04/20  5:00 PM              Tripura                       -   
1443  1444  29/04/20  5:00 PM          Uttarakhand                       -   
1444  1445  29/04/20  5:00 PM        Uttar Pradesh                       -   
1445  1446  29/04/20  5:00 PM          West Bengal                       -   

     ConfirmedForeignNational  Cured Deaths  Confirmed  
0                           0      0      0          1  
1                           0      0      0          1  
2                           0      0      0          2  
3                           0      0      0          3  
4                           0      0      0          3  
...                       ...    ...    ...        ...  
1441                        -    367     26       1012  
1442                        -      2      0          2  
1443                        -     34      0         54  
1444                        -    477     36       2115  
1445                        -    119     22        725  

[1446 rows x 9 columns]

In [4]:
Data.head()

Sno      Date     Time State/UnionTerritory ConfirmedIndianNational  \
0    1  30/01/20  6:00 PM               Kerala                       1   
1    2  31/01/20  6:00 PM               Kerala                       1   
2    3  01/02/20  6:00 PM               Kerala                       2   
3    4  02/02/20  6:00 PM               Kerala                       3   
4    5  03/02/20  6:00 PM               Kerala                       3   

  ConfirmedForeignNational  Cured Deaths  Confirmed  
0                        0      0      0          1  
1                        0      0      0          1  
2                        0      0      0          2  
3                        0      0      0          3  
4                        0      0      0          3

In [5]:
Data.tail()

Sno      Date     Time State/UnionTerritory ConfirmedIndianNational  \
1441  1442  29/04/20  5:00 PM            Telengana                       -   
1442  1443  29/04/20  5:00 PM              Tripura                       -   
1443  1444  29/04/20  5:00 PM          Uttarakhand                       -   
1444  1445  29/04/20  5:00 PM        Uttar Pradesh                       -   
1445  1446  29/04/20  5:00 PM          West Bengal                       -   

     ConfirmedForeignNational  Cured Deaths  Confirmed  
1441                        -    367     26       1012  
1442                        -      2      0          2  
1443                        -     34      0         54  
1444                        -    477     36       2115  
1445                        -    119     22        725

In [6]:
Data.shape

(1446, 9)

In [9]:
Data.columns


Index(['Sno', 'Date', 'Time', 'State/UnionTerritory',
       'ConfirmedIndianNational', 'ConfirmedForeignNational', 'Cured',
       'Deaths', 'Confirmed'],
      dtype='object')

In [10]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1446 entries, 0 to 1445
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Sno                       1446 non-null   int64 
 1   Date                      1446 non-null   object
 2   Time                      1446 non-null   object
 3   State/UnionTerritory      1446 non-null   object
 4   ConfirmedIndianNational   1446 non-null   object
 5   ConfirmedForeignNational  1446 non-null   object
 6   Cured                     1446 non-null   int64 
 7   Deaths                    1446 non-null   object
 8   Confirmed                 1446 non-null   int64 
dtypes: int64(3), object(6)
memory usage: 101.8+ KB


In [11]:
Data.describe()

Sno        Cured    Confirmed
count  1446.000000  1446.000000  1446.000000
mean    723.500000    46.941909   275.855463
std     417.568557   139.876142   758.945831
min       1.000000     0.000000     0.000000
25%     362.250000     0.000000     4.000000
50%     723.500000     3.000000    26.000000
75%    1084.750000    23.750000   178.500000
max    1446.000000  1388.000000  9318.000000

In [13]:
Data["State/UnionTerritory"].unique()

array(['Kerala', 'Telengana', 'Delhi', 'Rajasthan', 'Uttar Pradesh',
       'Haryana', 'Ladakh', 'Tamil Nadu', 'Karnataka', 'Maharashtra',
       'Punjab', 'Jammu and Kashmir', 'Andhra Pradesh', 'Uttarakhand',
       'Odisha', 'Puducherry', 'West Bengal', 'Chhattisgarh',
       'Chandigarh', 'Gujarat', 'Himachal Pradesh', 'Madhya Pradesh',
       'Bihar', 'Manipur', 'Mizoram', 'Andaman and Nicobar Islands',
       'Goa', 'Unassigned', 'Assam', 'Jharkhand', 'Arunachal Pradesh',
       'Tripura', 'Nagaland', 'Meghalaya', 'Nagaland#', 'Jharkhand#',
       'Madhya Pradesh#'], dtype=object)

DOING SPECIFICALLY FOR TAMIL NADU

In [14]:
Tamil_Nadu_Data=Data.loc[(Data["State/UnionTerritory"]=="Tamil Nadu")]   # loc function to get the coresponding rows  #all rows where the value in the "State/UnionTerritory" column is "Tamil Nadu" and assigns the resulting subset to a new DataFrame named Tamilnadu_df.

In [15]:
#Tamil_Nadu_Data

In [16]:
Tamil_Nadu_Data.head()

Sno      Date     Time State/UnionTerritory ConfirmedIndianNational  \
61    62  07/03/20  6:00 PM           Tamil Nadu                       1   
67    68  08/03/20  6:00 PM           Tamil Nadu                       1   
79    80  09/03/20  6:00 PM           Tamil Nadu                       1   
94    95  10/03/20  6:00 PM           Tamil Nadu                       1   
105  106  11/03/20  6:00 PM           Tamil Nadu                       1   

    ConfirmedForeignNational  Cured Deaths  Confirmed  
61                         0      0      0          1  
67                         0      0      0          1  
79                         0      0      0          1  
94                         0      0      0          1  
105                        0      0      0          1

In [17]:
Tamil_Nadu_Data.shape

(54, 9)

In [18]:
import plotly.offline as py 
import plotly.graph_objects as go

In [22]:
cured_rate= go.Scatter(x=Tamil_Nadu_Data["Date"],y=Tamil_Nadu_Data["Cured"],name="Cured Rate")
death_rate = go.Scatter(x=Tamil_Nadu_Data["Date"],y=Tamil_Nadu_Data["Deaths"],name="Deaths Rate")
py.iplot([cured_rate,death_rate])

In [23]:
Y=Tamil_Nadu_Data["Confirmed"]


In [24]:
Y

61         1
67         1
79         1
94         1
105        1
116        1
129        1
142        1
156        1
171        1
186        1
202        1
220        2
240        3
262        3
285        7
308        9
332       15
357       18
387       26
414       29
441       40
468       49
495       67
523       74
553      234
582      234
612      309
643      411
673      485
703      571
733      621
764      690
795      738
826      834
857      911
888      969
920     1075
953     1173
986     1204
1019    1242
1052    1267
1085    1323
1118    1372
1151    1477
1184    1520
1216    1596
1248    1629
1280    1683
1312    1755
1344    1821
1376    1885
1408    1937
1440    2058
Name: Confirmed, dtype: int64

In [25]:
Y.head()

61     1
67     1
79     1
94     1
105    1
Name: Confirmed, dtype: int64

In [26]:
Y.shape

(54,)

In [27]:
type(Y)

pandas.core.series.Series

In [28]:
Y=Y.values
type(Y)

numpy.ndarray

In [30]:
Y.shape

(54,)

In [31]:
train_size = int(len(Y)*0.80) 
test_size = len(Y) - train_size

In [32]:
train,test=Y[0:train_size ], Y[train_size:len(Y)]

In [33]:
train

array([   1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
          1,    2,    3,    3,    7,    9,   15,   18,   26,   29,   40,
         49,   67,   74,  234,  234,  309,  411,  485,  571,  621,  690,
        738,  834,  911,  969, 1075, 1173, 1204, 1242, 1267, 1323],
      dtype=int64)

In [34]:
test

array([1372, 1477, 1520, 1596, 1629, 1683, 1755, 1821, 1885, 1937, 2058],
      dtype=int64)

In [35]:
def create_dataset(dataset , look_back=1):
    data_x,data_y=[],[]
    for i in range(len(dataset)-look_back-1):
        a=dataset[i:i+look_back]
        data_x.append(a)
        data_y.append(dataset[i:i+look_back])
    return np.array(data_x),np.array(data_y)
    


In [36]:
look_back=2
train_x,train_y=create_dataset(train,look_back=2)
test_x,test_y=create_dataset(test,look_back=look_back)

In [37]:
train_x

array([[   1,    1],
       [   1,    1],
       [   1,    1],
       [   1,    1],
       [   1,    1],
       [   1,    1],
       [   1,    1],
       [   1,    1],
       [   1,    1],
       [   1,    1],
       [   1,    1],
       [   1,    2],
       [   2,    3],
       [   3,    3],
       [   3,    7],
       [   7,    9],
       [   9,   15],
       [  15,   18],
       [  18,   26],
       [  26,   29],
       [  29,   40],
       [  40,   49],
       [  49,   67],
       [  67,   74],
       [  74,  234],
       [ 234,  234],
       [ 234,  309],
       [ 309,  411],
       [ 411,  485],
       [ 485,  571],
       [ 571,  621],
       [ 621,  690],
       [ 690,  738],
       [ 738,  834],
       [ 834,  911],
       [ 911,  969],
       [ 969, 1075],
       [1075, 1173],
       [1173, 1204],
       [1204, 1242]], dtype=int64)

In [39]:
from sklearn.linear_model import LinearRegression

In [40]:
Model_LR=LinearRegression()

In [41]:
Model_LR.fit(train_x,train_y)

LinearRegression()

In [42]:
prediction=Model_LR.predict(test_x)
prediction


array([[1372., 1477.],
       [1477., 1520.],
       [1520., 1596.],
       [1596., 1629.],
       [1629., 1683.],
       [1683., 1755.],
       [1755., 1821.],
       [1821., 1885.]])

In [44]:
test_y

array([[1372, 1477],
       [1477, 1520],
       [1520, 1596],
       [1596, 1629],
       [1629, 1683],
       [1683, 1755],
       [1755, 1821],
       [1821, 1885]], dtype=int64)